sudo: required
language: cpp
dist: trusty

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev

compiler:
  - gcc

script:
  - cmake -G "Unix Makefiles" && make

os:
  - linux
