sudo: required
language: cpp
dist: trusty

compiler:
  - gcc

script:
  - cmake --version && python3 --version && cmake -G "Unix Makefiles" && make

os:
  - linux

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-test-dev
