sudo: required
language: cpp

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install cmake && sudo apt-get install cmake python3 ; fi

compiler:
  - gcc

script:
  - cmake -G "Unix Makefiles" && make

os:
  - linux
