language: cpp

before_install:
  - if ["$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get update -qq && sudo apt-get install python3; fi

compiler:
  - gcc

script:
  - cmake -G "Unix Makefiles" && make

os:
  - linux
